import { LinkedInProfile } from '../core/types.js';

export const KNOWN_SANDBOX_PROFILES: Record<string, LinkedInProfile> = {
  satyanadella: {
    profileUrl: 'https://www.linkedin.com/in/satyanadella',
    slug: 'satyanadella',
    urn: 'urn:li:fsd_profile:ACoAAAC1_0EBgZpM4qB3_8aX_example1',
    memberId: '7689123',
    publicIdentifier: 'satyanadella',
    fullName: 'Satya Nadella',
    firstName: 'Satya',
    lastName: 'Nadella',
    headline: 'Chairman and CEO at Microsoft',
    summary:
      'Chairman and Chief Executive Officer of Microsoft. On a mission to empower every person and every organization on the planet to achieve more.',
    location: {
      country: 'United States',
      city: 'Greater Seattle Area',
      state: 'Washington',
      raw: 'Greater Seattle Area, Washington, United States',
    },
    currentCompany: {
      name: 'Microsoft',
      title: 'Chairman and CEO',
      industry: 'Software Development',
      companyUrl: 'https://www.linkedin.com/company/microsoft',
      companyUrn: 'urn:li:fsd_company:1035',
      companyStaffCount: 220000,
    },
    profilePicture: {
      url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      expiresAt: null,
      rawUrn: 'urn:li:fsd_media:D4E03AQG_example',
    },
    backgroundPicture: {
      url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    },
    experience: [
      {
        id: 'exp_1',
        title: 'Chairman and CEO',
        companyName: 'Microsoft',
        companyUrl: 'https://www.linkedin.com/company/microsoft',
        companyUrn: 'urn:li:fsd_company:1035',
        location: 'Redmond, WA',
        startDate: 'Feb 2014',
        endDate: 'Present',
        duration: '12 yrs 7 mos',
        isCurrent: true,
        description: 'Leading Microsoft Corporation across global cloud, enterprise, and AI platforms.',
        employmentType: 'Full-time',
      },
      {
        id: 'exp_2',
        title: 'Executive Vice President, Cloud and Enterprise Engineering Group',
        companyName: 'Microsoft',
        companyUrl: 'https://www.linkedin.com/company/microsoft',
        location: 'Redmond, WA',
        startDate: '2011',
        endDate: '2014',
        duration: '3 yrs',
        isCurrent: false,
        description: 'Led the transformation of the business to the cloud infrastructure and services platform.',
        employmentType: 'Full-time',
      },
      {
        id: 'exp_3',
        title: 'Senior Vice President of R&D for the Online Services Division',
        companyName: 'Microsoft',
        companyUrl: 'https://www.linkedin.com/company/microsoft',
        location: 'Redmond, WA',
        startDate: '2007',
        endDate: '2011',
        duration: '4 yrs',
        isCurrent: false,
        description: 'Led search engine (Bing) engineering and online advertising platforms.',
        employmentType: 'Full-time',
      },
      {
        id: 'exp_4',
        title: 'Member of Technology Staff',
        companyName: 'Sun Microsystems',
        companyUrl: 'https://www.linkedin.com/company/sun-microsystems',
        location: 'Mountain View, CA',
        startDate: '1990',
        endDate: '1992',
        duration: '2 yrs',
        isCurrent: false,
        description: 'Software and systems engineering.',
        employmentType: 'Full-time',
      },
    ],
    education: [
      {
        id: 'edu_1',
        schoolName: 'The University of Chicago Booth School of Business',
        schoolUrl: 'https://www.linkedin.com/school/university-of-chicago-booth-school-of-business',
        degree: 'Master of Business Administration (M.B.A.)',
        fieldOfStudy: 'Business Administration and Management',
        startDate: '1994',
        endDate: '1997',
        activities: 'Executive MBA Program',
      },
      {
        id: 'edu_2',
        schoolName: 'University of Wisconsin-Milwaukee',
        schoolUrl: 'https://www.linkedin.com/school/university-of-wisconsin-milwaukee',
        degree: 'Master of Science (M.S.)',
        fieldOfStudy: 'Computer Science',
        startDate: '1988',
        endDate: '1990',
      },
      {
        id: 'edu_3',
        schoolName: 'Manipal Institute of Technology',
        schoolUrl: 'https://www.linkedin.com/school/manipal-institute-of-technology',
        degree: 'Bachelor of Engineering (B.Eng.)',
        fieldOfStudy: 'Electrical and Electronics Engineering',
        startDate: '1984',
        endDate: '1988',
      },
    ],
    skills: [
      { name: 'Cloud Computing', endorsementCount: 99 },
      { name: 'Enterprise Software', endorsementCount: 99 },
      { name: 'SaaS', endorsementCount: 95 },
      { name: 'Artificial Intelligence', endorsementCount: 99 },
      { name: 'Strategic Leadership', endorsementCount: 98 },
      { name: 'Product Management', endorsementCount: 90 },
      { name: 'Distributed Systems', endorsementCount: 88 },
      { name: 'Cross-functional Team Leadership', endorsementCount: 85 },
    ],
    certifications: [
      {
        name: 'Executive Management Certificate',
        issuingAuthority: 'Stanford Executive Program',
        issueDate: '2005',
      },
    ],
    languages: [
      { name: 'English', proficiency: 'Native or bilingual proficiency' },
      { name: 'Telugu', proficiency: 'Native or bilingual proficiency' },
      { name: 'Hindi', proficiency: 'Professional working proficiency' },
    ],
    contactInfo: {
      emails: ['satya.nadella@microsoft.com', 'satya@microsoft.com'],
      professionalEmail: 'satya.nadella@microsoft.com',
      phones: [],
      websites: ['https://news.microsoft.com/exec/satya-nadella/'],
      twitter: 'satyanadella',
      birthday: null,
      address: 'Redmond, Washington, USA',
    },
    connectionCount: 500,
    followerCount: 11200000,
    isInfluencer: true,
    isCreator: true,
    isPremium: true,
    meta: {
      fetchedAt: new Date().toISOString(),
      dataSource: 'sandbox_demo',
      processingTimeMs: 145,
    },
  },

  williamhgates: {
    profileUrl: 'https://www.linkedin.com/in/williamhgates',
    slug: 'williamhgates',
    urn: 'urn:li:fsd_profile:ACoAAAAb_0EBgZpM4qB3_8aX_example2',
    memberId: '251749',
    publicIdentifier: 'williamhgates',
    fullName: 'Bill Gates',
    firstName: 'Bill',
    lastName: 'Gates',
    headline: 'Co-chair, Bill & Melinda Gates Foundation',
    summary:
      'Co-chair of the Bill & Melinda Gates Foundation. Founder of Breakthrough Energy. Co-founder of Microsoft. Voracious reader, avid traveler, active blogger at Gates Notes.',
    location: {
      country: 'United States',
      city: 'Seattle',
      state: 'Washington',
      raw: 'Seattle, Washington, United States',
    },
    currentCompany: {
      name: 'Bill & Melinda Gates Foundation',
      title: 'Co-chair',
      industry: 'Philanthropy',
      companyUrl: 'https://www.linkedin.com/company/bill-&-melinda-gates-foundation',
      companyUrn: 'urn:li:fsd_company:16538',
      companyStaffCount: 2000,
    },
    profilePicture: {
      url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      expiresAt: null,
      rawUrn: 'urn:li:fsd_media:D4E03AQG_example_gates',
    },
    backgroundPicture: {
      url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    },
    experience: [
      {
        id: 'exp_g1',
        title: 'Co-chair',
        companyName: 'Bill & Melinda Gates Foundation',
        companyUrl: 'https://www.linkedin.com/company/bill-&-melinda-gates-foundation',
        location: 'Seattle, WA',
        startDate: '2000',
        endDate: 'Present',
        duration: '26 yrs',
        isCurrent: true,
        description: 'Guiding the foundation’s grantmaking and advocacy across global health, education, and development.',
      },
      {
        id: 'exp_g2',
        title: 'Founder',
        companyName: 'Breakthrough Energy',
        companyUrl: 'https://www.linkedin.com/company/breakthrough-energy',
        location: 'Kirkland, WA',
        startDate: '2015',
        endDate: 'Present',
        duration: '11 yrs',
        isCurrent: true,
        description: 'Supporting the innovations that will lead the world to net-zero greenhouse gas emissions.',
      },
      {
        id: 'exp_g3',
        title: 'Co-founder and Former CEO',
        companyName: 'Microsoft',
        companyUrl: 'https://www.linkedin.com/company/microsoft',
        location: 'Redmond, WA',
        startDate: '1975',
        endDate: '2008',
        duration: '33 yrs',
        isCurrent: false,
        description: 'Co-founded Microsoft with Paul Allen. Served as CEO and Chief Software Architect.',
      },
    ],
    education: [
      {
        id: 'edu_g1',
        schoolName: 'Harvard University',
        schoolUrl: 'https://www.linkedin.com/school/harvard-university',
        degree: 'Honorary Doctorate',
        fieldOfStudy: 'Law',
        startDate: '1973',
        endDate: '1975',
      },
      {
        id: 'edu_g2',
        schoolName: 'Lakeside School',
        degree: 'High School Diploma',
        fieldOfStudy: 'General Studies',
        startDate: '1968',
        endDate: '1973',
      },
    ],
    skills: [
      { name: 'Global Health', endorsementCount: 99 },
      { name: 'Philanthropy', endorsementCount: 99 },
      { name: 'Clean Energy & Climate Innovation', endorsementCount: 99 },
      { name: 'Software Development', endorsementCount: 99 },
      { name: 'Public Speaking', endorsementCount: 95 },
    ],
    certifications: [],
    languages: [{ name: 'English', proficiency: 'Native or bilingual proficiency' }],
    contactInfo: {
      emails: ['bill.gates@gatesfoundation.org'],
      professionalEmail: 'bill.gates@gatesfoundation.org',
      phones: [],
      websites: ['https://www.gatesnotes.com'],
      twitter: 'BillGates',
    },
    connectionCount: 500,
    followerCount: 36000000,
    isInfluencer: true,
    isCreator: true,
    isPremium: true,
    meta: {
      fetchedAt: new Date().toISOString(),
      dataSource: 'sandbox_demo',
      processingTimeMs: 120,
    },
  },

  reidhoffman: {
    profileUrl: 'https://www.linkedin.com/in/reidhoffman',
    slug: 'reidhoffman',
    urn: 'urn:li:fsd_profile:ACoAAAB_0EBgZpM4qB3_8aX_example3',
    memberId: '1001',
    publicIdentifier: 'reidhoffman',
    fullName: 'Reid Hoffman',
    firstName: 'Reid',
    lastName: 'Hoffman',
    headline: 'Partner at Greylock, Co-founder LinkedIn, Host of Masters of Scale',
    summary:
      'Entrepreneur and investor. Co-founder of LinkedIn. Partner at Greylock. Host of Masters of Scale podcast. Author of Blitzscaling, The Alliance, and The Start-up of You.',
    location: {
      country: 'United States',
      city: 'San Francisco Bay Area',
      state: 'California',
      raw: 'San Francisco Bay Area, California, United States',
    },
    currentCompany: {
      name: 'Greylock',
      title: 'General Partner',
      industry: 'Venture Capital & Private Equity',
      companyUrl: 'https://www.linkedin.com/company/greylock',
      companyUrn: 'urn:li:fsd_company:1234',
    },
    profilePicture: {
      url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    },
    backgroundPicture: {
      url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    },
    experience: [
      {
        id: 'exp_r1',
        title: 'Partner',
        companyName: 'Greylock',
        companyUrl: 'https://www.linkedin.com/company/greylock',
        location: 'Menlo Park, CA',
        startDate: '2009',
        endDate: 'Present',
        duration: '17 yrs',
        isCurrent: true,
        description: 'Investing in entrepreneurs building category-defining companies.',
      },
      {
        id: 'exp_r2',
        title: 'Co-founder & Executive Chairman',
        companyName: 'LinkedIn',
        companyUrl: 'https://www.linkedin.com/company/linkedin',
        location: 'Mountain View, CA',
        startDate: '2002',
        endDate: '2016',
        duration: '14 yrs',
        isCurrent: false,
        description: 'Co-founded LinkedIn and served as founding CEO and Executive Chairman.',
      },
    ],
    education: [
      {
        id: 'edu_r1',
        schoolName: 'University of Oxford',
        degree: 'Master of Studies (MSt)',
        fieldOfStudy: 'Philosophy',
        startDate: '1990',
        endDate: '1993',
      },
      {
        id: 'edu_r2',
        schoolName: 'Stanford University',
        degree: 'Bachelor of Science (BS)',
        fieldOfStudy: 'Symbolic Systems and Cognitive Science',
        startDate: '1986',
        endDate: '1990',
      },
    ],
    skills: [
      { name: 'Venture Capital', endorsementCount: 99 },
      { name: 'Entrepreneurship', endorsementCount: 99 },
      { name: 'Start-ups', endorsementCount: 99 },
      { name: 'Strategic Partnerships', endorsementCount: 95 },
      { name: 'Blitzscaling', endorsementCount: 94 },
    ],
    certifications: [],
    languages: [{ name: 'English', proficiency: 'Native or bilingual proficiency' }],
    contactInfo: {
      emails: ['reid.hoffman@greylock.com'],
      professionalEmail: 'reid.hoffman@greylock.com',
      phones: [],
      websites: ['https://reidhoffman.org'],
      twitter: 'reidhoffman',
    },
    connectionCount: 500,
    followerCount: 2800000,
    isInfluencer: true,
    isCreator: true,
    isPremium: true,
    meta: {
      fetchedAt: new Date().toISOString(),
      dataSource: 'sandbox_demo',
      processingTimeMs: 130,
    },
  },
};

export function generateDynamicSandboxProfile(slug: string): LinkedInProfile {
  // Convert slug like "john-doe-1234" to "John Doe"
  const cleanedSlug = slug.replace(/[0-9-]+$/g, '').replace(/-/g, ' ').trim();
  const nameParts = cleanedSlug.split(' ').filter(Boolean);
  const firstName = nameParts.length > 0 ? capitalize(nameParts[0]) : 'Alex';
  const lastName = nameParts.length > 1 ? capitalize(nameParts.slice(1).join(' ')) : 'Rivers';
  const fullName = `${firstName} ${lastName}`;

  return {
    profileUrl: `https://www.linkedin.com/in/${slug}`,
    slug: slug,
    urn: `urn:li:fsd_profile:dyn_${slug}`,
    memberId: `mem_${Math.abs(hashString(slug))}`,
    publicIdentifier: slug,
    fullName,
    firstName,
    lastName,
    headline: `Principal Software Engineer & Technical Lead`,
    summary: `Passionate technology leader with 8+ years of experience architecting distributed cloud systems, modern APIs, and high-throughput data platforms. Committed to engineering excellence, scalability, and user-centric software design.`,
    location: {
      country: 'United States',
      city: 'San Francisco',
      state: 'California',
      raw: 'San Francisco Bay Area, California, United States',
    },
    currentCompany: {
      name: 'Tech Innovations Inc',
      title: 'Principal Software Engineer',
      industry: 'Software Development',
      companyUrl: 'https://www.linkedin.com/company/tech-innovations',
      companyUrn: 'urn:li:fsd_company:98765',
      companyStaffCount: 1500,
    },
    profilePicture: {
      url: `https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80`,
      expiresAt: null,
    },
    backgroundPicture: {
      url: 'https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=1200&q=80',
    },
    experience: [
      {
        id: `exp_dyn_1`,
        title: 'Principal Software Engineer',
        companyName: 'Tech Innovations Inc',
        companyUrl: 'https://www.linkedin.com/company/tech-innovations',
        location: 'San Francisco, CA',
        startDate: 'Jan 2022',
        endDate: 'Present',
        duration: '4 yrs 2 mos',
        isCurrent: true,
        description: 'Leading core platform architecture, microservices modernization, and developer tooling across distributed teams.',
        employmentType: 'Full-time',
      },
      {
        id: `exp_dyn_2`,
        title: 'Senior Backend Engineer',
        companyName: 'CloudScale Systems',
        location: 'Austin, TX',
        startDate: 'Aug 2018',
        endDate: 'Dec 2021',
        duration: '3 yrs 5 mos',
        isCurrent: false,
        description: 'Engineered high-concurrency event ingestion pipelines processing over 500M events/day using Node.js, Go, and Kafka.',
        employmentType: 'Full-time',
      },
      {
        id: `exp_dyn_3`,
        title: 'Software Engineer',
        companyName: 'NextGen Solutions',
        location: 'Seattle, WA',
        startDate: 'Jun 2016',
        endDate: 'Jul 2018',
        duration: '2 yrs 2 mos',
        isCurrent: false,
        description: 'Developed full-stack web applications, RESTful APIs, and relational database integrations.',
        employmentType: 'Full-time',
      },
    ],
    education: [
      {
        id: `edu_dyn_1`,
        schoolName: 'University of California, Berkeley',
        degree: 'Bachelor of Science (B.S.)',
        fieldOfStudy: 'Computer Science',
        startDate: '2012',
        endDate: '2016',
        grade: '3.8 GPA',
        activities: 'ACM Chapter President, Hackathon Organizer',
      },
    ],
    skills: [
      { name: 'TypeScript', endorsementCount: 45 },
      { name: 'Node.js', endorsementCount: 52 },
      { name: 'Distributed Systems', endorsementCount: 38 },
      { name: 'PostgreSQL', endorsementCount: 34 },
      { name: 'Docker & Kubernetes', endorsementCount: 29 },
      { name: 'Cloud Architecture (AWS / GCP)', endorsementCount: 41 },
      { name: 'System Design', endorsementCount: 36 },
    ],
    certifications: [
      {
        name: 'AWS Certified Solutions Architect – Professional',
        issuingAuthority: 'Amazon Web Services (AWS)',
        issueDate: '2023',
      },
    ],
    languages: [
      { name: 'English', proficiency: 'Native or bilingual proficiency' },
      { name: 'Spanish', proficiency: 'Conversational' },
    ],
    contactInfo: {
      emails: [`${firstName.toLowerCase()}.${lastName.toLowerCase()}@techinnovations.com`],
      professionalEmail: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@techinnovations.com`,
      phones: [],
      websites: [`https://${slug}.dev`],
      twitter: slug,
    },
    connectionCount: 500,
    followerCount: 3420,
    isInfluencer: false,
    isCreator: true,
    isPremium: false,
    meta: {
      fetchedAt: new Date().toISOString(),
      dataSource: 'sandbox_demo',
      processingTimeMs: 165,
    },
  };
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

function hashString(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0;
  }
  return hash;
}
